### ISSUE TITLE
LinkedHashMap should use doubly linked list to store the insertion order

### ISSUE THREAD

**Issue by renjinghai** [zelenski/stanford-cpp-library#18]
Current implementation of LinkedHashMap use a vector to store the insertion order.
The time complexity of remove is O(N).
However, doubly linked list can be used to store the insertion order.
Then the time complexity of remove is O(1).

**Comment by stepp** [comment]
Can you please clarify?  How can a doubly-linked list perform an O(1) removal?

**Comment by renjinghai** [comment]
Each node in doubly linked list has previous and next pointers. It doesn't need visit all the elements to remove a node O(N). It just change node.prev.next and node.next.prev to remove the node O(1).
https://en.m.wikipedia.org/wiki/Doubly_linked_list#/editor/6

**Comment by zelenski** [comment]
LinkedHashMap is no more
