### ISSUE TITLE
XCopy Fixes not present in MadLibs.pro, QMAKE_COPY not recursive

### ISSUE THREAD

**Issue by Timvrakas** [zelenski/stanford-cpp-library#21]
First, the change to QMAKE_COPY is not present in the first homework assignment. I'm not sure how that system works, but thought you should know.

Second, when the QMAKE_COPY is used, it fails to copy recursively. replacing with QMAKE_COPY_DIR worked for me, but no idea how this would effect standard windows environments.

Tim

**Comment by zelenski** [comment]
Vestigial
