### ISSUE TITLE
GRect overrides final method `paint` and `scale`

### ISSUE THREAD

**Issue by wlnirvana** [zelenski/stanford-cpp-library#54]
The `JavaBackEnd/eclipseproject/src/acm/graphics/GObject.java` declares `paint` as a final method, while the `JavaTaskForce/src/acm/graphics/GRect.java` inheriting from `GObject` implements the `paint` method again.

Am I using mismatched versions of these files? Did I miss anything?

**Comment by zelenski** [comment]
Vestigial
