### ISSUE TITLE
`Grid<T>::locations()` appears nonempty for 0 x m and n x 0 grids.

### ISSUE THREAD

**Issue by htiek** [zelenski/stanford-cpp-library#64]
The `Grid<T>::locations()` function returns a `GridLocationRange` spanning the whole `Grid`. If the `Grid` has dimension m x 0 or 0 x n, the `GridLocationRange` will appear nonempty and looping over its contents will produce indices that are out of range. Therefore, code like this may crash:

    Grid<T> grid(0, 4);
    for (GridLocation loc: grid.locations()) {
        cout << grid[loc] << endl;
    }
    
The expected behavior here would be to have the loop not visit any locations.

**Comment by zelenski** [comment]
Fixed and merged 43bae5
