### ISSUE TITLE
Errors on macOS font loading

### ISSUE THREAD

**Issue by htiek** [zelenski/stanford-cpp-library#66]
Running code using the libraries on macOS generates warning messages about missing font aliases that display to stderr. Surprisingly, these seem to happen even for installed fonts like Didot and Monaco. I'm not sure whether this is

- an issue with Qt 6,
- an issue with our libraries, or
- an issue with my Old School MacBook Air.

Either way, it would be good to track this down and fix it; this warning message is concerning to students even though it's not their fault.

**Comment by zelenski** [comment]
I have also seen this message in past, but not recently and not sure if it that means Qt fixed something or I am just not using correct steps to trigger. @htiek if you can share reproducible case, would appreciate it!

**Comment by zelenski** [comment]
Aha -- there was a fix for this I had jammed into SimpleTest as quick hack, I propagated to the library to fix for all time.
c47626accbea0a67690e9c72a5f51fcfdc22f447
