### ISSUE TITLE
Inconsistency between `readEntireFile` overloads and `readEntireStream` overloads.

### ISSUE THREAD

**Issue by htiek** [zelenski/stanford-cpp-library#68]
Currently, there are two versions of the `readEntireFile` function. One takes in the name of a file and returns a `std::string` with the contents. The other takes in a filename and a `Vector<string>&`, then populates the `Vector<string>`.

There's also a `readEntireStream` function. It has two overloads. One returns a `string` containing the contents of the file. The other takes in a `string` by reference and overwrites it with the contents of the stream.

We should consider making these functions more consistent with one another. Perhaps all versions should work with `Vector<string>`? Or, alternatively, maybe we should remove the ones that take reference parameters and have them just return `string`s? From there the client could `stringSplit` them apart if that's what they want.

**Comment by zelenski** [comment]
Agreed! All of filelib/strlib API could use a thorough pass to cleanup and curate. Also could use a readBinaryFile (for huffman) that doesn't open in text mode and get unwanted newline conversion

**Comment by zelenski** [comment]
b8afba3663bae1c0700e0f3994e3333e2b9fc528 
The API is now
`Vector<string> readLines(ifstream)`
`string readEntire(ifstream)` 
These two cover majority of the common use cases.

**Comment by zelenski** [comment]
b8afba3663bae1c0700e0f3994e3333e2b9fc528
