### ISSUE TITLE
Add default constructor to `GRectangle`

### ISSUE THREAD

**Issue by htiek** [zelenski/stanford-cpp-library#72]
The `GRectangle` type currently has no default constructor, so it's not possible to declare a variable of type `GRectangle` without an initializer (e.g. `GRectangle rect;` does not compile). This is a consequence of [this earlier commit](https://github.com/zelenski/stanford-cpp-library/commit/2b920f87c5b009d391e073b4d13c2c81c268b504) that fixed a separate issue whereby `GRectangle` could be initialized to a `double` or without all the needed initializers.

**Comment by zelenski** [comment]
Added in 51f1807868e3fd0f3049fa81bc8f8a3fa4606953
